---

version: "3.8"

services:

  redis72-stack:
    image: redis/redis-stack-server:7.2.0-RC2
    ports:
      - ${REDIS_72_PORT}:6379
    entrypoint:
      - /opt/redis-stack/bin/redis-stack-server
      - --protected-mode no
      - --enable-module-command yes
      - --enable-debug-command yes
    volumes:
      - './redis/redis72.conf:/redis.conf'      
    profiles:
      - redis72
      - standalone
      - all

  redis70-stack:
    image: redis/redis-stack-server:7.0.6-RC2
    ports:
      - ${REDIS_70_PORT}:6379
    entrypoint:
      - /opt/redis-stack/bin/redis-stack-server
      - --protected-mode no
      - --enable-module-command yes
      - --enable-debug-command yes
    volumes:
      - './redis/redis70.conf:/redis.conf'      
    profiles:
      - redis70
      - standalone
      - all

  redis62-stack:
    image: redis/redis-stack-server:6.2.6-v7
    ports:
      - ${REDIS_62_PORT}:6379
    entrypoint:
      - /opt/redis-stack/bin/redis-stack-server
      - --protected-mode no
    volumes:
      - './redis/redis62.conf:/redis.conf'      
    profiles:
      - redis62
      - standalone
      - all

  redis72-sentinel:     
    build:
      context: .
      dockerfile: Dockerfile.sentinel
      args:
        PORT: ${REDIS_72_SENTINEL_MASTER_PORT}
    ports:
     - ${REDIS_72_SENTINEL_MASTER_PORT}:${REDIS_72_SENTINEL_MASTER_PORT}
     - ${REDIS_72_SENTINEL_REPLICA_1_PORT}:${REDIS_72_SENTINEL_REPLICA_1_PORT}
     - ${REDIS_72_SENTINEL_REPLICA_2_PORT}:${REDIS_72_SENTINEL_REPLICA_2_PORT}
     - ${REDIS_72_SENTINEL_1_PORT}:${REDIS_72_SENTINEL_1_PORT}
     - ${REDIS_72_SENTINEL_2_PORT}:${REDIS_72_SENTINEL_2_PORT}
     - ${REDIS_72_SENTINEL_3_PORT}:${REDIS_72_SENTINEL_3_PORT}
    profiles:
      - redis72
      - sentinel
      - all
