ARG PORT
FROM redis/redis-stack-server:7.2.0-RC2

COPY sentinel/create_sentinels.sh /create_sentinels.sh
COPY sentinel/sentinel.conf /sentinel.conf

RUN chmod a+x /create_sentinels.sh

ENTRYPOINT [ "/create_sentinels.sh", $PORT]
